apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/part-of: pacman
  name: mongodb
  namespace: jduimovich-tenant
spec:
  path: /
  port:
    targetPort: 27017
  to:
    kind: Service
    name: mongodb
    weight: null
status: {}
