apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: frontend-mongo-pacman-yp4r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: frontend-mongo-pacman-yp4r
    app.kubernetes.io/part-of: pacman
  name: frontend-mongo-pacman-yp4r
  namespace: jduimovich-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: frontend-mongo-pacman-yp4r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: frontend-mongo-pacman-yp4r
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
        image: quay.io/redhat-appstudio/user-workload@sha256:36d7d9bde0cb01ad0f5876e89cc0894caee82f29a14412386e216dabbab12068
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
