apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: mongodb
  namespace: jduimovich-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:17c4f1d441aca0f99b3e73689e25ea0f304d34510015285d8d5f32275f3055bc
        name: container-image
        resources: {}
status: {}
